Name: Unit tests

on:
  push:
    branches: [main]
  pull_request:
    brances: [main]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: | 
        #pipe above tells code that the data are below
          cd test/unit
          python -m unittest test_utils
